# Generated by Django 3.1.5 on 2021-01-04 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=64, verbose_name='Movie Title')),
                ('synopsis', models.CharField(max_length=512, verbose_name='Synopsis')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('text', models.CharField(max_length=512, verbose_name='User Review')),
                ('star_rating', models.FloatField(verbose_name='Star Rating')),
                ('created_on', models.DateField(auto_now=True, verbose_name='Reviewed On')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Movie Reviewer')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_reviews.movies', verbose_name='Reviewed Movies')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('id',),
            },
        ),
    ]
