# Generated by Django 3.1.5 on 2021-01-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0003_auto_20210105_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='missing title', max_length=64, verbose_name='Review Title'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(default='unknown movie', max_length=128, verbose_name='Movie Title'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(verbose_name='Review Text'),
        ),
    ]
